dataset:
  ag_news:
    validation_size: 20000

A: 
  output_dir: ".\\A\\results"
  distilbert_base_uncased:
    name: "distilbert_base_uncased_pt"
    evaluate: True
  bert_base_uncased:
    name: "bert_base_uncased_pt"
    evaluate: True
  bert_large_uncased:
    name: "bert_large_uncased_pt"
    evaluate: False
  camembert_base:
    name: "camembert_base"
    evaluate: False
  roberta_base:
    name: "roberta_base"
    evaluate: True

B:
  logs_dir: ".\\B\\logs"
  distilbert_base_uncased:
    log_name: "DistilBertUncased_LoRA-SEQ_CLS-q_lin.csv"
