name: dlnlp24

dependencies: 
  - python=3.9
  - pip=22.1.*
  - pip: 
    - numpy==1.26.*
    - torch==2.2.*
    - torchvision==0.17.*
    # - --index-url https://download.pytorch.org/whl/cu121
    - transformers==4.39.*
    - accelerate==0.29.*
    - scikit-learn==1.4.*
    - omegaconf==2.3.*
    - datasets==2.18.*
    - peft==0.10.*
    - evaluate==0.4.*
    - tqdm==4.66.*
    - matplotlib==3.8.*